MvcMovie/Controllers/KrepselisController.cs
using Microsoft.AspNetCore.Mvc;

namespace MvcMovie.Controllers
{
    public class KrepselisController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Buy()
        {
            return View();
        }
    }
}

MvcMovie/Controllers/ProfilisController.cs
using Microsoft.AspNetCore.Mvc;

namespace MvcMovie.Controllers
{
    public class ProfilisController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Update()
        {
            return View();
        }
        public IActionResult AddAddress()
        {
            return View();
        }
    }
}

MvcMovie/Controllers/RegistracijaController.cs
using Microsoft.AspNetCore.Mvc;

namespace MvcMovie.Controllers
{
    public class RegistracijaController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

MvcMovie/Controllers/UzsakymasController.cs
using Microsoft.AspNetCore.Mvc;
using MvcMovie.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcMovie.Controllers
{
    public class UzsakymasController : Controller
    {
        public IActionResult Index()
        {
            List<Uzsakymas> uzsakymas = new List<Uzsakymas>();
            Uzsakymas uzsakymas1 = new Uzsakymas() {
                Id = 1,
                Date = DateTime.Today,
                Price = 10,
                Status = "Vykdomas",
                Rated = false
            };

            Uzsakymas uzsakymas2 = new Uzsakymas()
            {
                Id = 2,
                Date = DateTime.Today,
                Price = 10,
                Status = "Vykdomas",
                Rated = false
            };
            uzsakymas.Add(uzsakymas1);
            uzsakymas.Add(uzsakymas2);

            return View(uzsakymas);
        }

        public IActionResult Edit()
        {
            return View();
        }

        public IActionResult Rate()
        {
            return View();
        }
    }
}

MvcMovie/Views/Shared/_IndividualProductCard.cshtml
@model MvcMovie.Models.Preke

<div class="col-lg-4 col-md-6 pb-4 filter">
    <!-- Card-->
    <div class="card bg-white rounded shadow-sm" style="border:1px solid #222">
        <div class="card-body px-3 pt-3 pb-1 row">
            <div class="col-7"><label class="float-left">@Model.Name</label></div>
            <div class="col-5"><label class="float-right"><span class="text-info h5">@string.Format("{0:c0}", Model.Price)</span></label> </div>
        </div>
        <img class="card-img-top img-fluid d-block mx-auto mb-3" src="@Model.Image" alt="Card image cap" style=" height: 250px; ">
        <div class="card-body p-1 px-3 row">
            <div class="col-12">
                
                    <a asp-action="Update" asp-controller="Preke" class="btn btn-primary">Redaguoti</a>
                    
                    <a asp-action="Delete" class="btn btn-danger">Ištrinti</a>
                
            </div>
            <div class="col-12 pt-2" style="font-size:13px; text-align:justify">
                <p> @Model.Description</p>
            </div>
            <div class="col-12 p-1">
                <a asp-action="BuyAd"  class="btn btn-warning form-control btn-sm p-2" style="height:40px">Pirkti reklamą</a>
                <br><br />
                <a asp-action="Details" asp-route-id="" class="btn btn-dark form-control btn-sm p-2" style="height:40px">Peržiūrėti prekę</a>
            </div>
        </div>
    </div>
</div>

MvcMovie/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Kavinukė</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcMovie.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcMovie</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Preke" asp-action="Index">Prekės</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Uzsakymas" asp-action="Index">Užsakymas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Prisijungimas" asp-action="Index">Prisijungimas</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Registracija" asp-action="Index">Registracija</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Profilis" asp-action="Index">Profilis</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Rekomendacijos" asp-action="Index">Rekomendacijos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Krepselis" asp-action="Index">Krepšelis</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Kavinukė - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @*<script src="~/js/site.js" asp-append-version="true"></script>*@
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>